#!/bin/bash -x
#release_number=%RELEASE_NUMBER%

echo "...checking dependencies"
if ! diff -b -B -q front-monitor/package.json app/package.json > /dev/null ; then
  echo "downloading new dependencies"
  cp app/package.json front-monitor/
  npm install 
fi

cp -R front-monitor/node_modules app/

echo "...prepare cron for log rotate"
chmod +x /home/despegar/app/scripts/logrotate.sh
echo "0 0 * * * /home/despegar/app/scripts/logrotate.sh" >> mycron
crontab mycron
rm mycron

echo "...done INSTALL"