#!/bin/bash -x

echo "...checking dependencies"
if ! diff -b -B -q front-monitor/package.json app/package.json > /dev/null ; then
	echo "downloading new dependencies"
  	cp app/package.json front-monitor/
  	cd front-monitor
  	npm install 
  	cd ..
fi

if ! diff -b -B -q /home/despegar/app.bak/collector/collector-version /home/despegar/app/collector/collector-version > /dev/null ; then
	echo "Update version of front-monitor-collector.js"
    version=`cat /home/despegar/app/collector/collector-version`
	for server in `ssh -i /home/despegar/.ssh/hf-static-00 hf-static-01 "cat /etc/cluster.info" | sed "s/{/\n/g" | grep "\-0" | cut -d '"' -f 4`; do
		scp -i /home/despegar/.ssh/$server -rq /home/despegar/app/collector $server:/home/despegar/apache/www/public/front-monitor/js-versioned/$version
	done
fi

cp -R front-monitor/node_modules app/

echo "...prepare cron for log rotate"
chmod +x /home/despegar/app/scripts/logrotate.sh
echo "0 0 * * * /home/despegar/app/scripts/logrotate.sh" >> mycron
crontab mycron
rm mycron

echo "...done INSTALL"