#!/bin/bash -x

echo -e "Starting App.js ..." 
{
	cd app/
	/home/despegar/.nvm/v0.10.8/bin/forever start -a -l /var/log/despegar/forever/front-monitor.log --pidfile /var/run/despegar/forever.pid /home/despegar/app/app.js prod
} >> /dev/null

